apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
images:
  - name: myapp
    newName: sumitsinghrmga/eks-gitops-demo
    newTag: "5da01fe7ff7a7c8d4f3bc0627eeac239f5962991"
