apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
images:
  - name: myapp
    newName: sumitsinghrmga/eks-gitops-demo
    newTag: "923529e348d8801af797a9ef9c455101f4eb155e"
