apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - ../../base
images:
  - name: myapp
    newName: sumitsinghrmga/eks-gitops-demo
    newTag: "948bea68268d1495c49fea6b5a69ac763e27a35d"
